; Script generated by the Inno Setup Script Wizard.

#define MyAppName "Legenda"
#define MyAppVersion "0.10"
#define MyAppPublisher "MAURINSOFT"
#define MyAppURL "http://maurinsoft.com.br"
#define MyAppExeName "legenda.exe"
#define MyInstallExeName "setup_legenda_0010"

[Setup]
AppId={{E1E834B2-0809-2A2A-1712-EE1591930347}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={commonpf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=D:\projetos\maurinsoft\legenda\bin
OutputBaseFilename={#MyInstallExeName}
Compression=lzma
SolidCompression=yes

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"


[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Types]
Name: "LEGENDA"; Description: {cm:T_LEGENDA}

[Components]
Name: "LEGENDA"; Description: "Arquivos da LEGENDA"; Types: LEGENDA;

[CustomMessages]
T_LEGENDA=LEGENDA
TD_LEGENDA=Install LEGENDA

[Files]
; Executável principal
Source: "D:\projetos\maurinsoft\legenda\src\legenda.exe"; DestDir: "{app}"; Flags: ignoreversion
;Source: "D:\projetos\maurinsoft\legenda\src\srvouve.exe"; DestDir: "{app}"; Flags: ignoreversion


[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppExeName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
